# Generated by Django 6.0.6 on 2026-06-05 21:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horaires',
            field=models.CharField(blank=True, default='9h-18h', max_length=100),
        ),
        migrations.AlterField(
            model_name='fraudreport',
            name='fraud_id',
            field=models.CharField(default=api.models.generate_fraud_id, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=api.models.generate_transaction_id, max_length=32, unique=True),
        ),
    ]
