# Generated by Django 6.0.6 on 2026-06-06 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_horaires_alter_fraudreport_fraud_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la boutique (ex: Boutique Centre-Ville)', max_length=255)),
                ('adresse', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('horaires', models.CharField(blank=True, default='9h-18h', max_length=100)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspendue')], default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Solde par location', max_digits=12)),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_transactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='partner_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['partner', 'statut'], name='api_locatio_partner_c92096_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='api_locatio_latitud_670fa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('partner', 'adresse')},
        ),
    ]
