from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    APIRootView,
    APIDocsView,
    RegisterView,
    LoginView,
    MeView,
    UserProfileView,
    PartnerListView,
    WalletView,
    WalletWithdrawView,
    PaymentInitiateView,
    TransactionListCreateView,
    QRScanView,
    DashboardView,
    AdminUsersView,
    AdminTransactionsView,
    AdminFraudView,
    AdminCommissionView,
    SeedTestUsersView,
)

urlpatterns = [
    path('', APIRootView.as_view(), name='api-root'),
    path('docs/', APIDocsView.as_view(), name='api-docs'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/me/', UserProfileView.as_view(), name='user-profile'),
    path('partners/', PartnerListView.as_view(), name='partner-list'),
    path('wallet/', WalletView.as_view(), name='wallet'),
    path('wallet/withdraw/', WalletWithdrawView.as_view(), name='wallet-withdraw'),
    path('payments/initiate/', PaymentInitiateView.as_view(), name='payment-initiate'),
    path('transactions/', TransactionListCreateView.as_view(), name='transactions'),
    path('qr/scan/', QRScanView.as_view(), name='qr-scan'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/users/', AdminUsersView.as_view(), name='admin-users'),
    path('admin/transactions/', AdminTransactionsView.as_view(), name='admin-transactions'),
    path('admin/fraud/', AdminFraudView.as_view(), name='admin-fraud'),
    path('admin/commissions/', AdminCommissionView.as_view(), name='admin-commissions'),
    path('debug/seed/', SeedTestUsersView.as_view(), name='debug-seed'),
]
